### ISSUE TITLE
Right side picture info

### ISSUE THREAD

**Issue by jakobvibe** [jakobvibe/photoIndex#3]
Add a picture info bar on the right side of the picture to show exif data

**Comment by Wertisdk** [comment]
76f5d8e1c303472553a9c2108f15382bade60e12
55eef34d6f9910c52df8469022638d784c75acd9eb38175270f4ec8812f7a8343445418f952cb362

**Comment by Wertisdk** [comment]
55eef34d6f9910c52df8469022638d784c75acd9
eb38175270f4ec8812f7a8343445418f952cb362
76f5d8e1c303472553a9c2108f15382bade60e12
