### ISSUE TITLE
Problems with pictures in folders with UTF8 characters in folder name

### ISSUE THREAD

**Issue by jakobvibe** [jakobvibe/photoIndex#7]

**Comment by jakobvibe** [comment]
It's looks like a general problem :) All text are encoded with utf8 in the json file.

I have seen the problem in filename, folders, image description, artist...

**Comment by Wertisdk** [comment]
The problem seems to be present in the generated json file where several texts contain double-encoded characters. Could the root cause for the issue be the exif data from the photos being saved with different encodings? Assigning the issue back to @jakobvibe

**Comment by jakobvibe** [comment]
The JSON file is now single encodede with commit: 
https://github.com/jakobvibe/photoIndex/commit/a03fc1cf0e74f31464c02a1685a327d4448fa8d1

Original problem is still alive... reassigning @Wertisdk
